export const ionToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlMzY4M2M5Zi0wZTQzLTQ5YjQtYmM0Mi1iMWU2YTVkZTEwNWIiLCJpZCI6NTU2NiwiaWF0IjoxNjE1NDc0MTg3fQ.9fKBFuVtsTEqmJNyNtP57M2zfYUOMhJgSMiA3aYnmmM'
export default {
  ionToken
}
